# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AudioTool(object):
    def setupUi(self, AudioTool):
        AudioTool.setObjectName("AudioTool")
        AudioTool.setWindowModality(QtCore.Qt.NonModal)
        AudioTool.resize(848, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AudioTool.sizePolicy().hasHeightForWidth())
        AudioTool.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/instruments/assets/instruments/nota.webp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AudioTool.setWindowIcon(icon)
        AudioTool.setStyleSheet("background-color: #6c7b95;")
        self.centralwidget = QtWidgets.QWidget(AudioTool)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Options = QtWidgets.QTabWidget(self.centralwidget)
        self.Options.setStyleSheet("")
        self.Options.setTabPosition(QtWidgets.QTabWidget.North)
        self.Options.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.Options.setElideMode(QtCore.Qt.ElideRight)
        self.Options.setUsesScrollButtons(True)
        self.Options.setDocumentMode(True)
        self.Options.setTabsClosable(False)
        self.Options.setMovable(True)
        self.Options.setTabBarAutoHide(True)
        self.Options.setObjectName("Options")
        self.Sintesis = QtWidgets.QWidget()
        self.Sintesis.setObjectName("Sintesis")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Sintesis)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.Sintesis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 75))
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.select_file = QtWidgets.QPushButton(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_file.sizePolicy().hasHeightForWidth())
        self.select_file.setSizePolicy(sizePolicy)
        self.select_file.setStyleSheet(":active{\n"
"    image: url(:/botones/assets/buttons/file.png);\n"
"}\n"
"\n"
":hover{\n"
"    image: url(:/botones/assets/buttons/file_hoover.png);\n"
"}\n"
"\n"
":pres{\n"
"    image: url(:/botones/assets/buttons/file_press.png)\n"
"}")
        self.select_file.setText("")
        self.select_file.setObjectName("select_file")
        self.horizontalLayout_4.addWidget(self.select_file)
        self.midi_name = QtWidgets.QLabel(self.widget_4)
        self.midi_name.setStyleSheet("color: rgb(255, 255, 255);")
        self.midi_name.setObjectName("midi_name")
        self.horizontalLayout_4.addWidget(self.midi_name)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.count_down = QtWidgets.QLabel(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.count_down.sizePolicy().hasHeightForWidth())
        self.count_down.setSizePolicy(sizePolicy)
        self.count_down.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.count_down.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.count_down.setObjectName("count_down")
        self.horizontalLayout_4.addWidget(self.count_down)
        self.media_buttons_widget = MediaButtonsWidget(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.media_buttons_widget.sizePolicy().hasHeightForWidth())
        self.media_buttons_widget.setSizePolicy(sizePolicy)
        self.media_buttons_widget.setObjectName("media_buttons_widget")
        self.horizontalLayout_4.addWidget(self.media_buttons_widget)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.view_zone = QtWidgets.QWidget(self.Sintesis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view_zone.sizePolicy().hasHeightForWidth())
        self.view_zone.setSizePolicy(sizePolicy)
        self.view_zone.setObjectName("view_zone")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.view_zone)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.track_seter = QtWidgets.QWidget(self.view_zone)
        self.track_seter.setObjectName("track_seter")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.track_seter)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.track_set = QtWidgets.QScrollArea(self.track_seter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.track_set.sizePolicy().hasHeightForWidth())
        self.track_set.setSizePolicy(sizePolicy)
        self.track_set.setMinimumSize(QtCore.QSize(250, 0))
        self.track_set.setAutoFillBackground(True)
        self.track_set.setFrameShape(QtWidgets.QFrame.Panel)
        self.track_set.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.track_set.setWidgetResizable(True)
        self.track_set.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.track_set.setObjectName("track_set")
        self.track_setter = QtWidgets.QWidget()
        self.track_setter.setGeometry(QtCore.QRect(0, 0, 256, 278))
        self.track_setter.setObjectName("track_setter")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.track_setter)
        self.verticalLayout.setObjectName("verticalLayout")
        self.track_0 = TrackConfigWidget(self.track_setter)
        self.track_0.setToolTip("")
        self.track_0.setAutoFillBackground(False)
        self.track_0.setStyleSheet("QWidget {\n"
"    border-style: solid;\n"
"    background-color: rgb(81, 76, 149);\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.track_0.setObjectName("track_0")
        self.verticalLayout.addWidget(self.track_0)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.track_set.setWidget(self.track_setter)
        self.verticalLayout_4.addWidget(self.track_set)
        self.sintetizar = QtWidgets.QPushButton(self.track_seter)
        self.sintetizar.setStyleSheet("color: rgb(255, 255, 255);")
        self.sintetizar.setObjectName("sintetizar")
        self.verticalLayout_4.addWidget(self.sintetizar)
        self.save = QtWidgets.QPushButton(self.track_seter)
        self.save.setStyleSheet("color: rgb(255, 255, 255);")
        self.save.setObjectName("save")
        self.verticalLayout_4.addWidget(self.save)
        self.horizontalLayout_3.addWidget(self.track_seter)
        self.track_view = QtWidgets.QScrollArea(self.view_zone)
        self.track_view.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.track_view.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.track_view.setWidgetResizable(True)
        self.track_view.setObjectName("track_view")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 508, 352))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scroll_2 = QtWidgets.QScrollArea(self.scrollAreaWidgetContents_2)
        self.scroll_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.scroll_2.setWidgetResizable(True)
        self.scroll_2.setObjectName("scroll_2")
        self.working_effects = QtWidgets.QWidget()
        self.working_effects.setGeometry(QtCore.QRect(0, 0, 486, 99))
        self.working_effects.setObjectName("working_effects")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.working_effects)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.working_effects)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.scroll_2.setWidget(self.working_effects)
        self.verticalLayout_3.addWidget(self.scroll_2)
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.widget_3 = QtWidgets.QWidget(self.frame_2)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.work_track = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.work_track.sizePolicy().hasHeightForWidth())
        self.work_track.setSizePolicy(sizePolicy)
        self.work_track.setWordWrap(True)
        self.work_track.setObjectName("work_track")
        self.verticalLayout_6.addWidget(self.work_track)
        self.choose_effect = QtWidgets.QComboBox(self.widget_3)
        self.choose_effect.setObjectName("choose_effect")
        self.verticalLayout_6.addWidget(self.choose_effect)
        self.to_song = QtWidgets.QRadioButton(self.widget_3)
        self.to_song.setObjectName("to_song")
        self.verticalLayout_6.addWidget(self.to_song)
        self.to_track = QtWidgets.QRadioButton(self.widget_3)
        self.to_track.setObjectName("to_track")
        self.verticalLayout_6.addWidget(self.to_track)
        self.discard_effect = QtWidgets.QPushButton(self.widget_3)
        self.discard_effect.setObjectName("discard_effect")
        self.verticalLayout_6.addWidget(self.discard_effect)
        self.horizontalLayout_9.addWidget(self.widget_3)
        self.scroll = QtWidgets.QScrollArea(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll.sizePolicy().hasHeightForWidth())
        self.scroll.setSizePolicy(sizePolicy)
        self.scroll.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.scroll.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scroll.setWidgetResizable(True)
        self.scroll.setObjectName("scroll")
        self.effect_container = QtWidgets.QWidget()
        self.effect_container.setGeometry(QtCore.QRect(0, 0, 361, 201))
        self.effect_container.setObjectName("effect_container")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.effect_container)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.effect_0 = EffectPropertyWidget(self.effect_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.effect_0.sizePolicy().hasHeightForWidth())
        self.effect_0.setSizePolicy(sizePolicy)
        self.effect_0.setObjectName("effect_0")
        self.horizontalLayout_10.addWidget(self.effect_0)
        self.scroll.setWidget(self.effect_container)
        self.horizontalLayout_9.addWidget(self.scroll)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.track_view.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_3.addWidget(self.track_view)
        self.verticalLayout_2.addWidget(self.view_zone)
        self.Options.addTab(self.Sintesis, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame = QtWidgets.QFrame(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.plot_track = QtWidgets.QComboBox(self.frame)
        self.plot_track.setObjectName("plot_track")
        self.verticalLayout_7.addWidget(self.plot_track)
        self.widget_2 = QtWidgets.QWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.plot_time = QtWidgets.QTimeEdit(self.widget_2)
        self.plot_time.setFrame(False)
        self.plot_time.setCurrentSection(QtWidgets.QDateTimeEdit.MinuteSection)
        self.plot_time.setTime(QtCore.QTime(0, 0, 0))
        self.plot_time.setObjectName("plot_time")
        self.horizontalLayout_2.addWidget(self.plot_time)
        self.verticalLayout_7.addWidget(self.widget_2)
        self.widget_5 = QtWidgets.QWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.widget_5)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.plot_long = QtWidgets.QSpinBox(self.widget_5)
        self.plot_long.setFrame(False)
        self.plot_long.setObjectName("plot_long")
        self.horizontalLayout_5.addWidget(self.plot_long)
        self.verticalLayout_7.addWidget(self.widget_5)
        self.plot_work = QtWidgets.QPushButton(self.frame)
        self.plot_work.setObjectName("plot_work")
        self.verticalLayout_7.addWidget(self.plot_work)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.horizontalLayout_6.addWidget(self.frame)
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setObjectName("widget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.plot_space = QtWidgets.QStackedWidget(self.widget)
        self.plot_space.setObjectName("plot_space")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.plot_space.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.plot_space.addWidget(self.page_2)
        self.verticalLayout_11.addWidget(self.plot_space)
        self.tool_bar = QtWidgets.QStackedWidget(self.widget)
        self.tool_bar.setObjectName("tool_bar")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.tool_bar.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.tool_bar.addWidget(self.page_4)
        self.verticalLayout_11.addWidget(self.tool_bar)
        self.horizontalLayout_6.addWidget(self.widget)
        self.Options.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_3 = QtWidgets.QFrame(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_7 = QtWidgets.QWidget(self.frame_3)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.widget_7)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.note_freq = QtWidgets.QSpinBox(self.widget_7)
        self.note_freq.setFrame(False)
        self.note_freq.setMinimum(28)
        self.note_freq.setMaximum(4186)
        self.note_freq.setObjectName("note_freq")
        self.horizontalLayout_8.addWidget(self.note_freq)
        self.verticalLayout_8.addWidget(self.widget_7)
        self.widget_8 = QtWidgets.QWidget(self.frame_3)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_5 = QtWidgets.QLabel(self.widget_8)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_11.addWidget(self.label_5)
        self.note_time = QtWidgets.QSpinBox(self.widget_8)
        self.note_time.setFrame(False)
        self.note_time.setObjectName("note_time")
        self.horizontalLayout_11.addWidget(self.note_time)
        self.verticalLayout_8.addWidget(self.widget_8)
        self.widget_9 = QtWidgets.QWidget(self.frame_3)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_6 = QtWidgets.QLabel(self.widget_9)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_12.addWidget(self.label_6)
        self.note_duration = QtWidgets.QSpinBox(self.widget_9)
        self.note_duration.setFrame(False)
        self.note_duration.setObjectName("note_duration")
        self.horizontalLayout_12.addWidget(self.note_duration)
        self.verticalLayout_8.addWidget(self.widget_9)
        self.widget_10 = QtWidgets.QWidget(self.frame_3)
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_7 = QtWidgets.QLabel(self.widget_10)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_13.addWidget(self.label_7)
        self.note_volume = QtWidgets.QSlider(self.widget_10)
        self.note_volume.setMaximum(127)
        self.note_volume.setOrientation(QtCore.Qt.Horizontal)
        self.note_volume.setObjectName("note_volume")
        self.horizontalLayout_13.addWidget(self.note_volume)
        self.verticalLayout_8.addWidget(self.widget_10)
        self.note_instrument = QtWidgets.QComboBox(self.frame_3)
        self.note_instrument.setObjectName("note_instrument")
        self.verticalLayout_8.addWidget(self.note_instrument)
        self.note_add = QtWidgets.QPushButton(self.frame_3)
        self.note_add.setObjectName("note_add")
        self.verticalLayout_8.addWidget(self.note_add)
        self.horizontalLayout_7.addWidget(self.frame_3)
        self.widget_6 = QtWidgets.QWidget(self.tab_2)
        self.widget_6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.scrollArea = QtWidgets.QScrollArea(self.widget_6)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.note_area = QtWidgets.QWidget()
        self.note_area.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.note_area.setObjectName("note_area")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.note_area)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem3 = QtWidgets.QSpacerItem(20, 356, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem3)
        self.scrollArea.setWidget(self.note_area)
        self.verticalLayout_9.addWidget(self.scrollArea)
        self.note_play = QtWidgets.QPushButton(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.note_play.sizePolicy().hasHeightForWidth())
        self.note_play.setSizePolicy(sizePolicy)
        self.note_play.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.note_play.setObjectName("note_play")
        self.verticalLayout_9.addWidget(self.note_play)
        self.horizontalLayout_7.addWidget(self.widget_6)
        self.Options.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.Options)
        AudioTool.setCentralWidget(self.centralwidget)

        self.retranslateUi(AudioTool)
        self.Options.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(AudioTool)

    def retranslateUi(self, AudioTool):
        _translate = QtCore.QCoreApplication.translate
        AudioTool.setWindowTitle(_translate("AudioTool", "Audio tool"))
        self.midi_name.setText(_translate("AudioTool", "Choose midi file..."))
        self.count_down.setText(_translate("AudioTool", "00:00"))
        self.media_buttons_widget.setToolTip(_translate("AudioTool", "Click and drag here"))
        self.media_buttons_widget.setWhatsThis(_translate("AudioTool", "Media buttons Widget.  "))
        self.track_0.setWhatsThis(_translate("AudioTool", "Track Config Widget.  "))
        self.sintetizar.setText(_translate("AudioTool", "Sintetizar"))
        self.save.setText(_translate("AudioTool", "Save"))
        self.label.setText(_translate("AudioTool", "Stay At Home"))
        self.work_track.setText(_translate("AudioTool", "Working on track"))
        self.to_song.setText(_translate("AudioTool", "All song"))
        self.to_track.setText(_translate("AudioTool", "Track"))
        self.discard_effect.setText(_translate("AudioTool", "Descartar"))
        self.effect_0.setToolTip(_translate("AudioTool", "Click and drag here"))
        self.effect_0.setWhatsThis(_translate("AudioTool", "Media buttons Widget.  "))
        self.Options.setTabText(self.Options.indexOf(self.Sintesis), _translate("AudioTool", "Sintesis"))
        self.label_2.setText(_translate("AudioTool", "Init time"))
        self.plot_time.setDisplayFormat(_translate("AudioTool", "m:ss"))
        self.label_3.setText(_translate("AudioTool", "Duration"))
        self.plot_work.setText(_translate("AudioTool", "Plot"))
        self.Options.setTabText(self.Options.indexOf(self.tab), _translate("AudioTool", "Espectrograma"))
        self.label_4.setText(_translate("AudioTool", "Frec"))
        self.label_5.setText(_translate("AudioTool", "Tiempo de inicio (s)"))
        self.label_6.setText(_translate("AudioTool", "Duracion (s)"))
        self.label_7.setText(_translate("AudioTool", "Volumen"))
        self.note_add.setText(_translate("AudioTool", "Agregar"))
        self.note_play.setText(_translate("AudioTool", "Play"))
        self.Options.setTabText(self.Options.indexOf(self.tab_2), _translate("AudioTool", "Notas"))

from FrontEnd.src.widgets.effectwidget import EffectPropertyWidget
from FrontEnd.src.widgets.mediabutton import MediaButtonsWidget
from FrontEnd.src.widgets.trackconfig import TrackConfigWidget
from FrontEnd.src.resources import buttons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AudioTool = QtWidgets.QMainWindow()
    ui = Ui_AudioTool()
    ui.setupUi(AudioTool)
    AudioTool.show()
    sys.exit(app.exec_())

